on: push
name: ğŸš€ CI/CD
jobs:
  web-deploy:
    name: ğŸ‰ Deployment to Cpanel
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code from Github repo
      uses: actions/checkout@v2
    
    - name: ğŸ“‚ Sync files between Github and Cpanel
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.petervandoorn.com
        username: petervan
        password: ${{ secrets.FTPPASSWORD }}
        server-dir: /public_html/
